### ISSUE TITLE
Projects using `sphinx_wagtail_theme` are not picking up the dependency for `sphinx_copybutton`

### ISSUE THREAD

**Issue by lb-** [wagtail/sphinx-wagtail-theme#225]
I would have expected that installing `sphinx_wagtail_theme` would also ensure that `sphinx_copybutton` is made available, but this seems to wrong.

When using this theme in Wagtail, we have to explicitly add `sphinx_copybutton`, it would be good if we did not have to do that. Unless it is kind of expected that this would be required manually.

## Expected solution

1. Add docs to this project to ensure that `sphinx_copybutton` is added by those using this theme
2. Explore/add whatever config 'magic' is needed to make this work automatically.

## See original comment

> (Regarding why it isn't picking up the dependency in sphinx_wagtail_theme - is that actually defined anywhere other than requirements.txt? That won't get picked up when packaging sphinx_wagtail_theme for pypi, unless there's some config magic I'm unaware of...)

_Originally posted by @gasman in https://github.com/wagtail/wagtail/issues/9339#issuecomment-1279132947_

## Relates to

- https://github.com/wagtail/sphinx_wagtail_theme/pull/219
- https://github.com/wagtail/sphinx_wagtail_theme/issues/45
- https://github.com/wagtail/wagtail/pull/9339

**Comment by lb-** [comment]
Note: I am new to package management in Python land so this could possibly be a complete confusion on my part about Python vs NPM package nested dependencies.

**Comment by gasman** [comment]
@mohammadareeb95 As mentioned in my comment quoted above - I'm pretty sure that putting it in requirements.txt is not enough for it to be handled automatically as a dependency when installing the package. requirements.txt is just a convenience for people setting up the package manually. To be a proper dependency, it needs to be defined in setup.py (at least, when using the traditional setuptools - for alternatives like [flit](https://flit.pypa.io/en/stable/) it might be different).

**Comment by laymonage** [comment]
We should add an `install_requires` to https://github.com/wagtail/sphinx-wagtail-theme/blob/main/setup.cfg based on the contents of https://github.com/wagtail/sphinx-wagtail-theme/blob/main/requirements.txt

Related: #289.

See also https://packaging.python.org/en/latest/discussions/install-requires-vs-requirements/

**Comment by laymonage** [comment]
After adding the package to `install_requires`, we need to add `app.setup_extension("sphinx_copybutton")` to our `setup()` function:

https://github.com/wagtail/sphinx-wagtail-theme/blob/25ccf6408139f9db09486c780ec86c1455f20d62/sphinx_wagtail_theme/__init__.py#L40-L51

And then, to test, remove `sphinx_copybutton` from the `extensions` list in our docs' config:

https://github.com/wagtail/sphinx-wagtail-theme/blob/25ccf6408139f9db09486c780ec86c1455f20d62/docs/conf.py#L13

If the copy button still shows up, then that means it's automatically picked up and users no longer have to explicitly install `sphinx_copybutton` and add it to their configuration.

If users already put `sphinx_copybutton` in `extensions`, they can safely remove it. Leaving it in there won't cause an error (but still recommended), as Sphinx gracefully handles multiple loads of the same extension:

- https://github.com/sphinx-doc/sphinx/blob/116a430caca98580c8877cf7b0ba270eae9604bf/sphinx/application.py#L429-L437
- https://github.com/sphinx-doc/sphinx/blob/116a430caca98580c8877cf7b0ba270eae9604bf/sphinx/registry.py#L441-L444
