### ISSUE TITLE
deployed documentation is not working

### ISSUE THREAD

**Issue by ashwin31** [wagtail/sphinx-wagtail-theme#241]
documentation in the readme.md pointing to https://sphinx-wagtail-theme.netlify.app/ is HTTP 404

**Comment by lb-** [comment]
We recently migrated to Vercel for hosting, I'm guessing you are referring to the GitHub link which now probably put of date. 

I'm not sure on the correct URL but this preview URL was generated on the PR that adopted Vercel. 

https://sphinx-wagtail-theme-wtojdzah7-wagtail.vercel.app/

https://github.com/wagtail/sphinx_wagtail_theme/pull/240

**Comment by lb-** [comment]
> Build Failed
> Command "npm run build && python3 -msphinx -M html docs/ _build" exited with 2
> ...
> Could not import extension sphinx.builders.linkcheck (exception: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'OpenSSL 1.0.2k-fips  26 Jan 2017'. See: https://github.com/urllib3/urllib3/issues/2168)

![Screenshot 2023-07-14 at 5 22 43 pm](https://github.com/wagtail/sphinx-wagtail-theme/assets/1396140/9f929d2a-47dc-4150-84cd-cd9c8e91728b)

Vercel build is still failing.

**Comment by thibaudcolas** [comment]
Closing in favour of https://github.com/wagtail/sphinx-wagtail-theme/issues/265, as the original issue is about the Netlify -> Vercel migration, and as far as I can tell preview builds were working fine from November 2022 till May 2023.
