### ISSUE TITLE
Code snippet copy button isn't visible when focused unless hovered

### ISSUE THREAD

**Issue by laymonage** [wagtail/sphinx-wagtail-theme#242]
The copy button on code snippets is only visible when it's hovered. When navigating with the keyboard, the focus can be moved to the copy button, but unless the block is hovered, it's confusing as we can't see where the focus is.

https://user-images.githubusercontent.com/6379424/203048961-77594399-30d1-4a0b-8ffc-07f9aeee49d9.mov

**Comment by lord2anil** [comment]
I would like to take this issue

**Comment by lb-** [comment]
PR up https://github.com/wagtail/sphinx-wagtail-theme/pull/259
