### ISSUE TITLE
Names in code are not styled with a monospace font

### ISSUE THREAD

**Issue by laymonage** [wagtail/sphinx-wagtail-theme#243]
Names in code (e.g. class, field, property, and method names) are not styled with a monospace font. This is because they do not use the `<code>` tag in the generated HTML and use a `<span class="pre">` instead, while we do not style the `.pre` class in our CSS.

This is very prominent in the [model reference](https://docs.wagtail.org/en/stable/reference/pages/model_reference.html) docs. I think using a monospace font for the names would make them more readable. Thus, we should update our styles to add the following rule:

```scss
.pre {
  font-family: $font-family-monospace;
}
```

**Comment by lord2anil** [comment]
I would like to take this issue

**Comment by msaini0r** [comment]
@laymonage can I work on this issue. plus do I need to change the color as well or only the font-family will be fine.

**Comment by lb-** [comment]
@msaini0r - start with just the font change and then compare with the plain `pre` element styling. The goal is that they look the same.

**Comment by msaini0r** [comment]
@lb- I am stuck in this issue. I was first making changes in index.html but then I realized we have already set the build in gitignore because its generated automatically. Can you tell me where should I look to solve this issue.

**Comment by lb-** [comment]
You will need to get the theme running locally and be able to make changes to SCSS files, re-run the build and then view those changes. 

The styles are located in this folder. https://github.com/wagtail/sphinx_wagtail_theme/tree/main/sass

Here are the development instructions. https://github.com/wagtail/sphinx_wagtail_theme/blob/main/docs/development.rst

**Comment by salty-ivy** [comment]
> @lb- I am stuck in this issue. I was first making changes in index.html but then I realized we have already set the build in gitignore because its generated automatically. Can you tell me where should I look to solve this issue.

@msaini0r make a draft i will help you out along the way XD in case if you need any help.

**Comment by salty-ivy** [comment]
> Names in code (e.g. class, field, property, and method names) are not styled with a monospace font. This is because they do not use the `<code>` tag in the generated HTML and use a `<span class="pre">` instead, while we do not style the `.pre` class in our CSS.
> 
> This is very prominent in the [model reference](https://docs.wagtail.org/en/stable/reference/pages/model_reference.html) docs. I think using a monospace font for the names would make them more readable. Thus, we should update our styles to add the following rule:
> 
> ```css-scss
> .pre {
>   font-family: $font-family-monospace;
> }
> ```

@msaini0r some elements in HTML parts uses `.pre` classes but `.pre` class has not styled you just need to check check which elements has `.pre` assigned then go to the corresponding scss associated to that html and style the it accordingly using the code snippet and then build the static assets again to check if changes occur, try to do it in few places initially to see the differences

**Comment by lb-** [comment]
PR up https://github.com/wagtail/sphinx-wagtail-theme/pull/260
