### ISSUE TITLE
Rename repository to sphinx-wagtail-theme for consistency

### ISSUE THREAD

**Issue by Stormheg** [wagtail/sphinx-wagtail-theme#256]
All other repositories in the wagtail organisation follow the kebab case convention (lowercase words separated by a hyphen).

I can't think of any reason why we cannot change the repository name.

---

I believe the current snake case name (lowercase words separated by an underscore) is inherited from the [sphinx_typo3_theme](https://github.com/TYPO3-Documentation/sphinx_typo3_theme) repository, which this theme is a fork of.

**Comment by lb-** [comment]
I'm all for this change, I don't have permission to do it though. GitHub should redirect any links by default. 

I might suggest we go for `wagtail-sphinx-theme` though as many others (majority?) have Wagtail first.

Maybe add to the next Core team agenda for a bit of feedback and check who can make the change. 

![Screenshot_20230603-163914](https://github.com/wagtail/sphinx_wagtail_theme/assets/1396140/a4900946-e11b-4f9f-9d2c-ab4fe50d4d95)

**Comment by laymonage** [comment]
The other repositories use `wagtail-` first because they're packages for Wagtail, while this is technically a package for Sphinx so it should probably be `sphinx-` first?

**Comment by lb-** [comment]
Good call - I didn't think of it that way. Sphinx prefix makes sense in this case.

**Comment by Stormheg** [comment]
Good call Sage!

**Comment by Scotchester** [comment]
We did it live! (In today's core team meeting.) Thanks for raising this, @Stormheg.
