### ISSUE TITLE
Release 6.1.0 / 6.1.1

### ISSUE THREAD

**Issue by lb-** [wagtail/sphinx-wagtail-theme#257]
### Release process

-   [x] `CONTRIBUTORS.md` is updated
-   [x] `CHANGELOG.md` is updated
-   [x] `setup.cfg` is updated (see `version`)
-   [ ] Everything is committed, clean checkout
-   [ ] `~/.pypirc` has a username and password (token)
-   [ ] Add a git tag and a GitHub release once completed

**Comment by lb-** [comment]
Planning to do a release alongside the next Wagtail release, I will review recently merged PRs, check the changelog and get this ready.

**Comment by lb-** [comment]
Thanks @laymonage  I have prepared a few PRs for review that should fix those items.

**Comment by lb-** [comment]
Update. Other small issues should be fixed, I would like to get https://github.com/wagtail/sphinx-wagtail-theme/pull/263 in but if no reviews or other problems I will look at doing a release v6 this weekend or next week.

**Comment by laymonage** [comment]
This link needs to be updated to Vercel:

https://github.com/wagtail/sphinx-wagtail-theme/blob/8d08f88794f535a22162c31bb8a52de8d8d493c0/README.md?plain=1#L10

**Comment by lb-** [comment]
@laymonage thanks for that, PR up https://github.com/wagtail/sphinx-wagtail-theme/pull/266

I updated to the RTD version as that seemed more correct, we use that at the top of the GitHub Page.

<img width="319" alt="Screenshot 2023-07-15 at 8 18 44 am" src="https://github.com/wagtail/sphinx-wagtail-theme/assets/1396140/32e59c5a-4b94-483d-a212-a0f153d08250">

**Comment by lb-** [comment]
https://pypi.org/project/sphinx-wagtail-theme/6.1.0/

**Comment by lb-** [comment]
This release has a broken icon font - https://github.com/wagtail/sphinx-wagtail-theme/issues/267

**Comment by lb-** [comment]
https://pypi.org/project/sphinx-wagtail-theme/6.1.1/
