### ISSUE TITLE
Automate release process

### ISSUE THREAD

**Issue by laymonage** [wagtail/sphinx-wagtail-theme#285]
Noticed a few things when I was releasing v6.3.0 just now:

- Our git tags are inconsistent: some start with `v`, some don't: https://github.com/wagtail/sphinx-wagtail-theme/tags
- In the release process guide, there are `prerelease` and `postrelease` commands that I don't know where they come from. They do not seem to be necessary.
- The `python -m build` command doesn't seem correct. It should be `python setup.py sdist bdist_wheel` or `make build`.
- The `requirements.txt` does not include `wheel` and `twine`, so these had to be installed separately. Either include them in the `requirements.txt`, or call this out explicitly.

That said, it would be nice to automate the release process using GitHub Actions. We already build the project in our CI config, we can add additional step that publishes the package using [the official PyPI action](https://github.com/pypa/gh-action-pypi-publish) and the [Trusted Publisher](https://docs.pypi.org/trusted-publishers/) configuration. I use this for modeladmin and it's working great: https://github.com/wagtail-nest/wagtail-modeladmin/blob/main/.github/workflows/publish.yml.

cc @Stormheg

**Comment by lb-** [comment]
I agree about the pre/postrelease - I have no idea where that comes from. It worked on my old laptop but not on my new one and in the last release I just manually created the changes.
