### ISSUE TITLE
Adopt latest Wagtail logo

### ISSUE THREAD

**Issue by lb-** [wagtail/sphinx-wagtail-theme#287]
Once https://github.com/wagtail/wagtail/issues/10404 is complete - review the PRs and adopt the relevant logos in the Sphinx theme.

* https://github.com/wagtail/sphinx-wagtail-theme/tree/main/sphinx_wagtail_theme/static/img
* https://github.com/wagtail/sphinx-wagtail-theme/blob/main/docs/favicon.ico

**Comment by OsafAliSayed** [comment]
@lb- should I be replacing the wagtail-logo.svg and wagtail-logo-new.svg with updated ones from core wagtail project?

**Comment by lb-** [comment]
Yep. But I'm not sure what the new one is for, maybe it's not needed.
