### ISSUE TITLE
Getting started guide not clear

### ISSUE THREAD

**Issue by songproducer** [wagtail/sphinx-wagtail-theme#292]
As a beginner in Wagtail, the usage instructions

> Select the “Sphinx Wagtail theme” in the conf.py file of a Sphinx project:

is confusing. How do I add this to Wagtail?

**Comment by laymonage** [comment]
Hi @songproducer, this package is a theme for Sphinx the documentation tool (https://www.sphinx-doc.org/en/master/). It's not something you would normally add to a Wagtail project itself.

Do you use Sphinx to build the documentation of your project?

**Comment by songproducer** [comment]
Hi @laymonage 
It seems I misunderstood the purpose of Sphinx. I thought it was a general purpose theming tool for Wagtail.
