### ISSUE TITLE
Footer has invisible links

### ISSUE THREAD

**Issue by smark-1** [wagtail/sphinx-wagtail-theme#306]
The footer has invisible text it shows created using ________ and ______. If you hover over them you can see it though.

![Image](https://github.com/user-attachments/assets/f99b69bd-97e3-4e04-bf79-4e0ef90ef9b8)

https://github.com/user-attachments/assets/dd9aa3f2-e0f6-4457-92a2-0f0e55c76de4

**Comment by laymonage** [comment]
This was already fixed in #302, but yet to be released.
